name: NotificationTest

on:
  push:
   branches:
     - DevPipelienes 

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    if: always()
    uses: dawidd6/action-send-mail@v2
      server_address:smtp.gmail.com
      server_port:465
	  username: ${{ secrets.EMAIL_USERNAME }}
	  password: ${{ secrets.EMAIL_PASSWORD }}
    subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    to: ${{ secrets.TO_EMAIL_ID }}
    from: Devops testing ID
